export const EnquiryData = [
    {
        img: "https://cdn.xxl.thumbs.canstockphoto.com/a-3d-human-character-a-word-no-stock-illustration_csp19967382.jpg",
        message: "wellCome",
        email: "ahmed@gmail.com",
        name: "ahmed",
        imgId: 1,
        phone: "1111",
        id: 1,
    },
    {
        img: "https://i.ytimg.com/vi/OZoVp0cvGBQ/maxresdefault.jpg",
        message: "wellCome",
        email: "mohammed@gmail.com",
        name: "mohammed",
        imgId: 2,
        phone: "2222",
        id: 2,
    },
    {
        img: "https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
        message: "wellCome",
        email: "omar@gmail.com",
        name: "omar",
        imgId: 3,
        phone: "3333",
        id: 3,
    },
    {
        img: "https://images.unsplash.com/photo-1533827432537-70133748f5c8",
        message: "wellCome",
        email: "tarek@gmail.com",
        name: "tarek",
        imgId: 4,
        phone: "4444",
        id: 4,
    },
    {
        img: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62",
        message: "wellCome",
        email: "soso@gmail.com",
        name: "soso",
        imgId: 5,
        phone: "55555",
        id: 5,
    },
    {
        img: "https://images.unsplash.com/photo-1516802273409-68526ee1bdd6",
        message: "",
        email: "momo@gmail.com",
        name: "momo",
        imgId: 6,
        phone: "",
        id: 6,
    },

];